### ISSUE TITLE
suggestions sometimes freaks out w/ NPE on auth

### ISSUE THREAD

**Issue by barneyb** [folded-ear/gobrennas-api#100]
Occasionally the call to get suggestions freaks out. Not always. Subsequent requests with the same headers are fine.

<img width="558" alt="image" src="https://github.com/user-attachments/assets/77e7e17a-a367-4944-b84c-0a6cf9d424e1">

`curl 'https://beta.api.gobrennas.com/graphql' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Content-Type: application/json' -H 'Referer: https://beta.gobrennas.com/' -H 'apollo-require-preflight: true' -H 'Origin: https://beta.gobrennas.com' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Connection: keep-alive' -H 'Cookie: _ga_H504GHJSBG=GS1.1.1726944511.372.1.1726944811.0.0.0; _ga=GA1.1.1541734871.1675023980; FTOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI4Nzc3NzQ5Njk4OTU5IiwiaWF0IjoxNzI2MzczOTY0LCJleHAiOjE3MjcyMzc5NjR9.-0PXrDDFxzdunR29l1cjzD2bYtQki-SBOgVg_u-MKKWw8MVh39cTHA77K9oRQofmJnzsjYA63yihLVM8HE2mqw' -H 'Priority: u=4' --data-raw '{"operationName":"getRecipeSuggestions","variables":{"first":3,"after":null},"query":"query getRecipeSuggestions($first: NonNegativeInt! = 9, $after: Cursor = null) {\n  library {\n    recipes: suggestRecipesToCook(first: $first, after: $after) {\n      ...librarySearchResult\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment librarySearchResult on RecipeConnection {\n  edges {\n    cursor\n    node {\n      id\n      owner {\n        id\n        imageUrl\n        email\n        name\n        __typename\n      }\n      photo {\n        url\n        focus\n        __typename\n      }\n      name\n      favorite\n      labels\n      externalUrl\n      calories\n      yield\n      totalTime\n      __typename\n    }\n    __typename\n  }\n  pageInfo {\n    hasNextPage\n    endCursor\n    __typename\n  }\n  __typename\n}"}'`

```
{
  "errors": [
    {
      "message": "Cannot invoke \"org.springframework.security.core.Authentication.isAuthenticated()\" because \"auth\" is null",
      "locations": [
        {
          "line": 29,
          "column": 7
        }
      ],
      "path": [
        "library",
        "recipes",
        "edges",
        0,
        "node",
        "favorite"
      ],
      "extensions": {
        "type": "NullPointerException",
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "library": null
  }
}
```

**Comment by barneyb** [comment]
I found an actual NPE too? Definitely screwybits to sort.

```
Exception while fetching data (/library/recipes/edges[0]/node/favorite) : Cannot invoke "org.springframework.security.core.Authentication.isAuthenticated()" because "auth" is null
java.lang.NullPointerException: Cannot invoke "org.springframework.security.core.Authentication.isAuthenticated()" because "auth" is null
	at com.brennaswitzer.cookbook.util.UserPrincipalAccessImpl.getUserPrincipal(UserPrincipalAccessImpl.java:23)
	at com.brennaswitzer.cookbook.util.UserPrincipalAccess.getId(UserPrincipalAccess.java:9)
	at com.brennaswitzer.cookbook.util.UserPrincipalAccessImpl.getUser(UserPrincipalAccessImpl.java:31)
	at com.brennaswitzer.cookbook.graphql.loaders.RecipeIsFavoriteBatchLoader.load(RecipeIsFavoriteBatchLoader.java:36)
	at org.dataloader.DataLoaderHelper.invokeListBatchLoader(DataLoaderHelper.java:436)
	at org.dataloader.DataLoaderHelper.invokeLoader(DataLoaderHelper.java:410)
	at org.dataloader.DataLoaderHelper.invokeLoader(DataLoaderHelper.java:337)
	at org.dataloader.DataLoaderHelper.dispatchQueueBatch(DataLoaderHelper.java:233)
	at org.dataloader.DataLoaderHelper.dispatch(DataLoaderHelper.java:199)
	at org.dataloader.DataLoader.dispatch(DataLoader.java:585)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.dataloader.DataLoaderRegistry.dispatchAll(DataLoaderRegistry.java:134)
	at graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach.dispatch(FieldLevelTrackingApproach.java:242)
	at graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach$1.onFieldValuesInfo(FieldLevelTrackingApproach.java:152)
	at graphql.execution.AsyncExecutionStrategy.lambda$execute$1(AsyncExecutionStrategy.java:72)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at graphql.execution.Async$Many.lambda$await$1(Async.java:125)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.dataloader.DataLoaderHelper.lambda$dispatchQueueBatch$2(DataLoaderHelper.java:260)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by barneyb** [comment]
This is a race between the data loaders and Spring's thread-local request context. Can't rely on Spring's `SecurityContextHolder` to still have an `Authentication` for the data loaders.

**Comment by barneyb** [comment]
Haven't been able to fully RCA this; it's a tight race. It _looks_ like it has to do with the doubled query for recommendations and search results. When there's only one query in flight, kickstart will use the main thread to service its data loads. If there are multiple queries in flight, it'll shunt all-but-one off to its threadpool to service. This makes sense: the `BatchLoader` _returns_ a `CompletionStage` for its results, but results may also be _requested_ asynchronously at a different execution layer.
